name: Package

on:
  push:
    branches: [ Spicetify-v2 ]

jobs:

  Build:

    name: Build
    runs-on: windows-2019
    if: "contains(github.event.head_commit.message, '+ PACKAGE')"

    steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v2
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v4.5.1'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          python setup.py install

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: './Spicetify-Easyinstall'

      - name: Build
        run: |
          cd .\Spicetify-Easyinstall
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec

      - name: Get short SHA string
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Zip package
        shell: cmd
        run: 7z a -r .\Spicetify-Easyinstall-${{ steps.short-sha.outputs.sha }}.zip .\Spicetify-Easyinstall\dist\windows\Spicetify-Easyinstall\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Spicetify-Easyinstall-${{ steps.short-sha.outputs.sha }}
          path: ./Spicetify-Easyinstall-${{ steps.short-sha.outputs.sha }}.zip

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
