name: Build Release Package

on:
  release:
    types: [ published ]

jobs:

  Build:

    name: Build
    runs-on: windows-2019

    steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v2
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v4.3'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          python setup.py install

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: './spicetify-easyinstall'

      - name: Set version
        run: |
          sed -i "s/\(globals.version =\) .*/\globals.version = '${{ github.event.release.tag_name }}'/" .\spicetify-easyinstall\spicetify-easyinstall.py

      - name: Build
        run: |
          cd .\spicetify-easyinstall
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec

      - name: Zip package
        shell: cmd
        run: 7z a -r .\spicetify-easyinstallV${{ github.event.release.tag_name }}.zip .\spicetify-easyinstall\dist\windows\spicetify-easyinstall\*

      - name: Publish package
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./spicetify-easyinstallV${{ github.event.release.tag_name }}.zip

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0

      - name: Delete skipped workflow runs
        uses: Willy-JL/delete-skipped-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
